Bogdan
bboddyya/CrossPosts-final pull request #1
Opened 2022-06-17 19:01 UTC by bboddyya

Основной функционал сделал, добавил еще локалсторэдж на посты. Доделал верстку до айфона во всех местах.

2022-06-19 15:41 UTC, IlyaAgarishev approved these changes, later dismissed

2022-06-19 15:41 UTC, IlyaAgarishev commented on src/Login/Login.js
> +      .filter((e) => e.length >= 1);
.trim()

2022-06-20 16:32 UTC, IlyaAgarishev requested changes

2022-06-20 16:32 UTC, IlyaAgarishev commented on src/Login/Login.js
> +    if (firstLettersArray.length > 1) {
if (firstLettersArray.length > 1) {
      return letters[0] + letters[1];
}
return letters[0]

2022-06-20 16:32 UTC, IlyaAgarishev commented on src/Pages/Credit/UI/Input.js
> +  const navigate = useNavigate("/tasks");
useNavigate не принимает параметров

2022-06-20 16:32 UTC, IlyaAgarishev commented on README.md
> +# Getting Started with Create React App
Опиши проект в ридми

2022-06-20 16:32 UTC, IlyaAgarishev commented on f
> +[33mcommit 644acbfef9f28369a3a183fe671592f9931c2d24[m[33m ([m[1;36mHEAD -> [m[1;32mmain[m[33m)[m
файлы артефакты удаляй

2022-06-20 16:32 UTC, IlyaAgarishev commented on public/robots.txt
> +User-agent: *
почисти проект от ненужный файлов

2022-06-20 16:32 UTC, IlyaAgarishev commented on src/App.js
> +        SinglePost,
Зачем компонент SinglePost в Контексте ?

2022-06-20 16:32 UTC, IlyaAgarishev commented on src/App.js
> +      <div className="App" style={darkMode ? themeColor.body : null}>
const getDarkStyle = (name) => {
    return darkMode ? themeColor[name] : null;
  };

2022-06-20 16:32 UTC, IlyaAgarishev commented on src/Header/Header.css
> +    background-color: white;
background-color

2022-06-20 16:32 UTC, IlyaAgarishev commented on src/Pages/About/About.js
> +        without the opportunity to <span className="el">EXPRESS</span>{" "}
className="el"

2022-06-20 16:32 UTC, IlyaAgarishev commented on src/Pages/Credit/UI/Input.js
> +      {
getTask()

2022-06-20 16:32 UTC, IlyaAgarishev commented on src/Pages/Credit/UI/Input.js
> +          onChange={(e) => setTitle(e.target.value)}
const onChange = (e) => setTitle(e.target.value);

....

onChange={onChange}

2022-06-20 16:32 UTC, IlyaAgarishev commented on src/Pages/Profile/Profile.js
> +  const loginName = () => setLogin(true);
const loginName = () => {
   setLogin(true);
 }

2022-06-20 16:32 UTC, IlyaAgarishev commented on src/Pages/Profile/Profile.js
> +          onChange={(e) => {
Вынести onChange

2022-06-20 16:32 UTC, IlyaAgarishev commented on src/Pages/SinglePost/SinglePost.js
> +    tasks.find((el) => JSON.stringify(el.id) === id) || "";
const { author, title, time, date, likes, replies, shares, picture } = useMemo(()=>{
return tasks.find((el) => JSON.stringify(el.id) === id)
},[id])

2022-06-20 16:32 UTC, IlyaAgarishev commented on src/Pages/SinglePost/SinglePost.js
> +          {picture ? (
picture  && <img ...>

2022-06-20 16:32 UTC, IlyaAgarishev commented on src/Pages/SinglePost/SinglePost.js
> +        {date}, 2022
`${time} . ${date} 2022`

2022-06-20 16:32 UTC, IlyaAgarishev commented on src/Pages/Tasks/UI/Post.js
> +              <Link to={`/tasks/${id}`} key={id}>
В отдельный компонент Task.


tasks.map((args)=> <Task {...args} />)

2022-06-20 16:32 UTC, IlyaAgarishev commented on src/Pages/Tasks/UI/Post.js
> +                      {picture ? (
picture  && ...

2022-06-20 16:32 UTC, IlyaAgarishev commented on src/Pages/Tasks/UI/Post.js
> +                    {time}
${time} . ${date} 2022

2022-06-20 16:32 UTC, IlyaAgarishev commented on src/Posts/defaultPosts.js
> +      date.getHours() +
В отдельную ф-ию getTime и не забывать про "``"

2022-06-20 16:32 UTC, IlyaAgarishev commented on src/Posts/defaultPosts.js
> +    date: date.getDate() + " мая",
`${date.getDate()} мая`

2022-06-20 16:32 UTC, IlyaAgarishev commented on src/Themes/ThemeSwitch.js
> +    darkMode === false ? setDarkMode(true) : setDarkMode(false);
setDarkMode(!darkMode)

2022-06-20 16:32 UTC, IlyaAgarishev commented on src/index.css
> +  /* height: 100vh; */
Все чо закомментировано - удалить

2022-06-20 19:26 UTC, IlyaAgarishev commented on src/Login/Login.js
> +    const arr = name.toString().split(" ");
Зачем `toString()` у `name`, если  `name` итак по дефолту должен быть string ?

2022-06-20 19:46 UTC, IlyaAgarishev commented on src/Login/Login.js
> +  function letters(name) {
1) Название поменять на getFirstTwoLetters
2) Ниже привожу пример ф-ии, которая в разы короче: 
`
const getFirstLetters = (name) => {
  const firstLetters = name
    .trim()
    .split(" ")
    .map(([el]) => {
      return el;
    })
    .join(" ");

  return firstLetters;
};

`

2022-06-21 14:27 UTC, IlyaAgarishev commented on src/Pages/Tasks/UI/Post.js
> +              <Task
Тут надо было так сделать:

```
tasks.map((props)=><Task {...props} />)
```

2022-06-21 16:39 UTC, bboddyya commented on src/Pages/Tasks/UI/Post.js
> +                      {picture ? (
тут два варианта отрисовки в зависимости от наличия picture.

2022-06-21 17:35 UTC, bboddyya commented on src/Login/Login.js
> +  function letters(name) {
Формула выводит не первые две буквы, а весь массив, добавил еще проверку 

if (firstLetters.length > 1) {
      return firstLetters[0] + firstLetters[1];
    }
    return firstLetters[0];
  };

2022-06-21 17:36 UTC, bboddyya commented on src/index.css
> +  /* height: 100vh; */
done

2022-06-21 17:36 UTC, bboddyya commented on src/Themes/ThemeSwitch.js
> +    darkMode === false ? setDarkMode(true) : setDarkMode(false);
done

2022-06-21 17:36 UTC, bboddyya commented on src/Posts/defaultPosts.js
> +    date: date.getDate() + " мая",
done

2022-06-21 17:36 UTC, bboddyya commented on src/Posts/defaultPosts.js
> +      date.getHours() +
done

2022-06-21 17:36 UTC, bboddyya commented on src/Pages/Tasks/UI/Post.js
> +                    {time}
done

2022-06-21 17:36 UTC, bboddyya commented on src/Pages/Tasks/UI/Post.js
> +                      {picture ? (
done

2022-06-21 17:36 UTC, bboddyya commented on src/Pages/Tasks/UI/Post.js
> +              <Link to={`/tasks/${id}`} key={id}>
done

2022-06-21 17:36 UTC, bboddyya commented on src/Pages/SinglePost/SinglePost.js
> +        {date}, 2022
done

2022-06-21 17:36 UTC, bboddyya commented on src/Pages/SinglePost/SinglePost.js
> +          {picture ? (
done

2022-06-21 17:36 UTC, bboddyya commented on src/Pages/SinglePost/SinglePost.js
> +    tasks.find((el) => JSON.stringify(el.id) === id) || "";
done

2022-06-21 17:36 UTC, bboddyya commented on src/Pages/Profile/Profile.js
> +          onChange={(e) => {
done

2022-06-21 17:36 UTC, bboddyya commented on src/Pages/Profile/Profile.js
> +  const loginName = () => setLogin(true);
done

2022-06-21 17:36 UTC, bboddyya commented on src/Pages/Credit/UI/Input.js
> +          onChange={(e) => setTitle(e.target.value)}
done

2022-06-21 17:36 UTC, bboddyya commented on src/Pages/Credit/UI/Input.js
> +      {
done

2022-06-21 17:36 UTC, bboddyya commented on src/Pages/About/About.js
> +        without the opportunity to <span className="el">EXPRESS</span>{" "}
done

2022-06-21 17:36 UTC, bboddyya commented on src/Header/Header.css
> +    background-color: white;
done

2022-06-21 17:36 UTC, bboddyya commented on src/App.js
> +      <div className="App" style={darkMode ? themeColor.body : null}>
done

2022-06-21 17:36 UTC, bboddyya commented on src/App.js
> +        SinglePost,
done

2022-06-21 17:36 UTC, bboddyya commented on public/robots.txt
> +User-agent: *
done

2022-06-21 17:36 UTC, bboddyya commented on f
> +[33mcommit 644acbfef9f28369a3a183fe671592f9931c2d24[m[33m ([m[1;36mHEAD -> [m[1;32mmain[m[33m)[m
done

2022-06-21 17:36 UTC, bboddyya commented on README.md
> +# Getting Started with Create React App
done

2022-06-21 17:36 UTC, bboddyya commented on src/Pages/Credit/UI/Input.js
> +  const navigate = useNavigate("/tasks");
done

2022-06-21 17:36 UTC, bboddyya commented on src/Login/Login.js
> +    if (firstLettersArray.length > 1) {
done

2022-06-22 13:54 UTC, IlyaAgarishev commented on src/Login/Login.js
> +  function letters(name) {
Просто добавь ф-ию slice(0,2) - она оставит только два первых элемента в массиве
```
const getFirstLetters = (name) => {
  const firstLetters = name
    .trim()
    .split(" ")
    .slice(0, 2)
    .map(([el]) => el)
    .join(" ");

  return firstLetters;
};
```

2022-06-22 17:33 UTC, bboddyya commented on src/Login/Login.js
> +  function letters(name) {
done

2022-06-23 05:49 UTC, IlyaAgarishev commented on src/Pages/SinglePost/SinglePost.js
>            style={picture ? { display: "block" } : { display: "none" }}
Тут по другому пишут:

```
style={{ display: picture ? "block" : "none" }}
```

2022-06-23 17:39 UTC, bboddyya commented on src/Pages/SinglePost/SinglePost.js
>            style={picture ? { display: "block" } : { display: "none" }}
**done**

2022-06-24 12:17 UTC, merged